import type { Metadata } from "next";
import { Poppins } from "next/font/google";
//importted cn from utils
import {cn} from "@/lib/utils";
import "./globals.css";
//importing theme provider from components
import { ThemeProvider } from "@/components/theme-provider";

//updated the font style to poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/*added the poppins and dark class here wraped in cn*/}
      <body className={cn(poppins.className)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> 
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
